name: Github4women wk

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *' # Executa cada hora

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run custom script
        run: ./scripts/custom-script.sh # Execute o script personalizado

      - name: Run custom script on schedule
        run: scripts/scripts/custom-scheduled-script.sh


    